version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    container_name: nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./database/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: a4b7a4b6
      MYSQL_USER: Profi
      MYSQL_PASSWORD: a4b7a4b7
      MYSQL_DATABASE: Test
    ports:
      - "8181:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: db
